version: "3"

services:
  mysqlihgroup:
    container_name: mysqlihgroup
    image: mysql:5.7
    restart: always
    volumes:
      - /usr/local/volumes/mysqlihgroup:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ihgroup
      MYSQL_USER: root
      MYSQL_PASSWORD: password

  wordpressihgroup:
    depends_on:
      - mysqlihgroup
    container_name: wordpressihgroup
    image: wordpress:latest
    restart: always
    expose:
      - "80"
    volumes:
      - /usr/local/volumes/wordpressihgroup/var/www/html:/var/www/html
      - ./conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      WORDPRESS_DB_HOST: mysqlihgroup:3306
      WORDPRESS_DB_NAME: ihgroup
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_TABLE_PREFIX: wp_
      VIRTUAL_HOST: ihgroup.pe, www.ihgroup.pe
      LETSENCRYPT_HOST: ihgroup.pe, www.ihgroup.pe
      LETSENCRYPT_EMAIL: kevin.silva.095@gmail.com
      APACHE_RUN_DIR: /var/run/apache2
    # command: apache2 -D FOREGROUND

networks:
  default:
    external:
      name: nginx-proxy_nginx-proxy