version: '3.0'

services:
  mysql2:
    container_name: mysql-2
    environment:
      MYSQL_DATABASE: wordpress-2
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
    image: mariadb:latest
    restart: unless-stopped
    volumes:
    - /usr/local/volumes/mysql-2/:/var/lib/mysql:rw
  wordpress2:
    container_name: wordpress-2
    depends_on:
    - mysql2
    environment:
      LETSENCRYPT_EMAIL: kevin.silva.095@gmail.com
      LETSENCRYPT_HOST: ecommerce.apps.com.pe,www.ecommerce.apps.com.pe
      VIRTUAL_HOST: ecommerce.apps.com.pe,www.ecommerce.apps.com.pe
      WORDPRESS_DB_HOST: mysql2:3306
      WORDPRESS_DB_NAME: wordpress-2
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_USER: root
      WORDPRESS_TABLE_PREFIX: wp_
    image: wordpress:latest
    logging:
      options:
        max-size: 200k
    restart: unless-stopped
    volumes:
    - /usr/local/volumes/wordpress-2/wordpress-core:/var/www/html:rw
    - ./conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini:rw

networks:
  default:
    external:
      name: webproxy